title: Weijia Peng
email: weijia.peng@rutgers.edu
description: >-
  Assistant Professor of Business Analytics and Finance,
  Jack Welch College of Business, Sacred Heart University
url: "https://weijiap.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social links (fill in your actual profile URLs)
scholar_url: "https://scholar.google.com/citations?user=siGxXQ0AAAAJ&hl=en"
linkedin_url: "https://www.linkedin.com/in/wjpeng/"
cv_url: "https://www.dropbox.com/scl/fi/p3sont2zh3fqel09kwtea/Weijia_Peng_CV.pdf?rlkey=z4cbk32d0yb6lkn6nj85gaaix&st=jig5ld4r&dl=0"
